#!/bin/bash
# build_loader.sh — regenerate the embedded remap loader dylib + byte header.
#
# The remap injection path (MIMachInjectorRemap) needs a real Mach-O dylib
# whose __TEXT is remapped into the target. We embed the dylib bytes into
# MIMachInjectorRemap.m via loader_arm64_remap_dylib.h and dump those bytes
# to a temp file at runtime. This script rebuilds the dylib from
# loader_arm64_remap.s + loader_arm64_remap_fixup.c + loader_arm64_remap_handoff.c,
# ad-hoc signs it, and rewrites the header.
#
# Run this manually whenever any of loader_arm64_remap.s /
# loader_arm64_remap_fixup.c / loader_arm64_remap_handoff.c changes.

set -euo pipefail
DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$DIR"

DYLIB="$(mktemp -t loader_arm64_remap).dylib"
trap 'rm -f "$DYLIB"' EXIT

echo "==> assembling loader_arm64_remap.s + loader_arm64_remap_fixup.c + loader_arm64_remap_handoff.c → $(basename "$DYLIB")"
# Flags rationale:
#   -fno-stack-protector: apply_fixups / perform_runtime_handoff run on a raw
#     mach thread with no TLS, so any __stack_chk_guard access would trap.
#   -fno-builtin -ffreestanding: prevent the compiler from lowering loops to
#     libc calls (memcpy/memset) — the loader must be self-contained.
#   -Oz: minimise code size; the whole dylib gets remapped into every target.
#   -fno-common -fvisibility=hidden: cleaner symbol table; only apply_fixups
#     and perform_runtime_handoff need external visibility so the .s file can
#     `bl` them.
clang -dynamiclib -arch arm64 -arch arm64e \
    -fno-stack-protector -fno-builtin -ffreestanding \
    -Oz -fno-common -fvisibility=hidden \
    -o "$DYLIB" \
    loader_arm64_remap.s \
    loader_arm64_remap_fixup.c \
    loader_arm64_remap_handoff.c

# Guard against silently shipping a stage-1 shim that hands libpthread a raw
# function pointer.
#
# pthread_create_from_mach_thread takes a `void *(*)(void *)`, which on arm64e
# is an IA/0-signed function pointer. libpthread re-signs it into its own struct
# and _pthread_start authenticates it before branching, so passing the raw
# adrp/add result poisons the pointer and the spawned thread dies with a
# PAC_EXCEPTION before a single instruction of _pthread_thunk runs — the target
# process is killed and nothing indicates why. It regressed exactly once, when
# the start routine moved from an injector-filled config slot to the
# loader-internal _pthread_thunk symbol and the signing did not come along.
#
# The check is here rather than in a unit test because the loader is a
# generated artifact: this script is the only place it is produced, and the
# bytes it emits are what every injection actually executes.
echo "==> verifying stage-1 signs the pthread start routine"
for SLICE_ARCHITECTURE in arm64 arm64e; do
    SLICE="$(mktemp -t loader_slice_${SLICE_ARCHITECTURE})"
    lipo -thin "$SLICE_ARCHITECTURE" "$DYLIB" -output "$SLICE"
    STAGE1_DISASSEMBLY="$(objdump --disassemble-symbols=_remap_stage1_entry "$SLICE")"
    rm -f "$SLICE"
    if ! grep -q "paciza" <<< "$STAGE1_DISASSEMBLY"; then
        echo "error: _remap_stage1_entry ($SLICE_ARCHITECTURE) never signs the pthread start" >&2
        echo "       routine. pthread_create_from_mach_thread needs an IA/0-signed" >&2
        echo "       function pointer; a raw one kills the target with a PAC_EXCEPTION." >&2
        echo "       Restore the 'paciza x2' in loader_arm64_remap.s." >&2
        exit 1
    fi
done

echo "==> ad-hoc signing (recipients ad-hoc verify byte-for-byte)"
codesign -f -s - "$DYLIB"

echo "==> regenerating loader_arm64_remap_dylib.h"
{
    echo "// AUTO-GENERATED by build_loader.sh — do not edit by hand."
    echo "//"
    echo "// Source: loader_arm64_remap.s + loader_arm64_remap_fixup.c"
    echo "// Fat: arm64 + arm64e, ad-hoc code-signed."
    echo "//"
    echo "// MIMachInjectorRemap.m writes this byte array to a temp file at runtime,"
    echo "// dlopens it in the injector, then mach_vm_remaps its __TEXT + __DATA"
    echo "// into the target process."
    echo
    xxd -i -n "MIMachInjectorRemapLoaderDylib" "$DYLIB"
} > loader_arm64_remap_dylib.h

echo "==> done. Header contains $(wc -c < "$DYLIB") bytes of loader dylib."
