#!/bin/bash
# build_loader.sh — regenerate the embedded remap loader dylib + byte header.
#
# The remap injection path (MIMachInjectorRemap) needs a real Mach-O dylib
# whose __TEXT is remapped into the target. We embed the dylib bytes into
# MIMachInjectorRemap.m via loader_arm64_remap_dylib.h and dump those bytes
# to a temp file at runtime. This script rebuilds the dylib from
# loader_arm64_remap.s + loader_arm64_remap_fixup.c + loader_arm64_remap_handoff.c,
# ad-hoc signs it, and rewrites the header.
#
# Run this manually whenever any of loader_arm64_remap.s /
# loader_arm64_remap_fixup.c / loader_arm64_remap_handoff.c changes.

set -euo pipefail
DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$DIR"

DYLIB="$(mktemp -t loader_arm64_remap).dylib"
trap 'rm -f "$DYLIB"' EXIT

echo "==> assembling loader_arm64_remap.s + loader_arm64_remap_fixup.c + loader_arm64_remap_handoff.c → $(basename "$DYLIB")"
# Flags rationale:
#   -fno-stack-protector: apply_fixups / perform_runtime_handoff run on a raw
#     mach thread with no TLS, so any __stack_chk_guard access would trap.
#   -fno-builtin -ffreestanding: prevent the compiler from lowering loops to
#     libc calls (memcpy/memset) — the loader must be self-contained.
#   -Oz: minimise code size; the whole dylib gets remapped into every target.
#   -fno-common -fvisibility=hidden: cleaner symbol table; only apply_fixups
#     and perform_runtime_handoff need external visibility so the .s file can
#     `bl` them.
clang -dynamiclib -arch arm64 -arch arm64e \
    -fno-stack-protector -fno-builtin -ffreestanding \
    -Oz -fno-common -fvisibility=hidden \
    -o "$DYLIB" \
    loader_arm64_remap.s \
    loader_arm64_remap_fixup.c \
    loader_arm64_remap_handoff.c

echo "==> ad-hoc signing (recipients ad-hoc verify byte-for-byte)"
codesign -f -s - "$DYLIB"

echo "==> regenerating loader_arm64_remap_dylib.h"
{
    echo "// AUTO-GENERATED by build_loader.sh — do not edit by hand."
    echo "//"
    echo "// Source: loader_arm64_remap.s + loader_arm64_remap_fixup.c"
    echo "// Fat: arm64 + arm64e, ad-hoc code-signed."
    echo "//"
    echo "// MIMachInjectorRemap.m writes this byte array to a temp file at runtime,"
    echo "// dlopens it in the injector, then mach_vm_remaps its __TEXT + __DATA"
    echo "// into the target process."
    echo
    xxd -i -n "MIMachInjectorRemapLoaderDylib" "$DYLIB"
} > loader_arm64_remap_dylib.h

echo "==> done. Header contains $(wc -c < "$DYLIB") bytes of loader dylib."
