#!/bin/bash
# build_loader.sh — regenerate the embedded remap loader dylib + byte header.
#
# The remap injection path (MIMachInjectorRemap) needs a real Mach-O dylib
# whose __TEXT is remapped into the target. We embed the dylib bytes into
# MIMachInjectorRemap.m via loader_arm64_remap_dylib.h and dump those bytes
# to a temp file at runtime. This script rebuilds the dylib from
# loader_arm64_remap.s, ad-hoc signs it, and rewrites the header.
#
# Run this manually whenever loader_arm64_remap.s changes.

set -euo pipefail
DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$DIR"

DYLIB="$(mktemp -t loader_arm64_remap).dylib"
trap 'rm -f "$DYLIB"' EXIT

echo "==> assembling loader_arm64_remap.s → $(basename "$DYLIB")"
clang -dynamiclib -arch arm64 -arch arm64e -o "$DYLIB" loader_arm64_remap.s

echo "==> ad-hoc signing (recipients ad-hoc verify byte-for-byte)"
codesign -f -s - "$DYLIB"

echo "==> regenerating loader_arm64_remap_dylib.h"
{
    echo "// AUTO-GENERATED by build_loader.sh — do not edit by hand."
    echo "//"
    echo "// Source: loader_arm64_remap.s"
    echo "// Fat: arm64 + arm64e, ad-hoc code-signed."
    echo "//"
    echo "// MIMachInjectorRemap.m writes this byte array to a temp file at runtime,"
    echo "// dlopens it in the injector, then mach_vm_remaps its __TEXT + __DATA"
    echo "// into the target process."
    echo
    xxd -i -n "MIMachInjectorRemapLoaderDylib" "$DYLIB"
} > loader_arm64_remap_dylib.h

echo "==> done. Header contains $(wc -c < "$DYLIB") bytes of loader dylib."
